- name: Check whether this customer shall be skipped
  when: skip_customer == true
  fail:
    msg: This customer must be skipped.

- name: Check whether easydb_url is missing
  when: easydb_url == ''
  fail:
    msg: Please fill the variable easydb_url!

- name: Check whether easydb_solution is missing
  when: easydb_solution == ''
  fail:
    msg: Please fill the variable easydb_solution!

- name: Check whether docker username is missing
  when: easydb_docker_user == ''
  fail:
    msg: Please fill the variable easydb_docker_user!

- name: Check whether docker password is missing
  when: easydb_docker_pass == ''
  fail:
    msg: Please fill the variable easydb_docker_pass!

- name: Check whether hotfolder is enabled but easydb_hotfolder_hostname is missing
  when: easydb_hotfolder_hostname == '' and easydb_hotfolder_enabled
  fail:
    msg: Please fill the variable easydb_hotfolder_hostname!

- name: Check whether easydb_mail_relay_for_ssmtp is missing
  when: easydb_mail_relay_for_ssmtp == ''
  fail:
    msg: Please define the variable easydb_mail_relay_for_ssmtp!

- name: Check whether easydb_hostname_for_ssmtp is missing
  when: easydb_hostname_for_ssmtp == ''
  fail:
    msg: Please define the variable easydb_hostname_for_ssmtp!

- name: Check whether easydb_envelope_from is missing
  when: easydb_envelope_from == ''
  fail:
    msg: Please define the variable easydb_envelope_from!

- name: Check whether objectstore misses datamodel uid
  when: easydb_objectstore_url != '' and easydb_datamodel_uid == ''
  fail:
    msg: Either set easydb_objectstore_url to empty string or set easydb_datamodel_uid!

- name: Check that easydb5_fylr_servers is in inventory
  when: not (groups.easydb5_fylr_servers is defined)
  fail:
    msg: "[easydb5_fylr_servers:children] is missing (e.g. in inventory/hosts.ini)"

- name: Check that fylr is either fully configured or not at all
  when: not (groups.easydb5_fylr_servers.0 is defined) and 'fylr' in easydb_containers_on_host[inventory_hostname]
  fail:
    msg: "easydb5_fylr_servers is empty BUT fylr is in easydb_containers_on_host"

- name: Check that eas_produce.json file exists, if easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled is true
  stat:
    path: {{ playbook_dir }}/eas.d/eas_produce.json
  register: p
  when: easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled and p.stat.exists
  fail:
    msg: "easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled is true, but eas_produce.json is missing at {{ playbook_dir }}/eas.d/"

- name: Check that eas_rights_management.yml file exists, if easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled is true
  stat:
    path: {{ playbook_dir }}/eas.d/eas_rights_management.yml
  register: p
  when: easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled and p.stat.exists
  fail:
    msg: "easydb_eas_custom_version_enabled or easydb_eas_watermark_enabled is true, but eas_rights_management.yml is missing at {{ playbook_dir }}/eas.d/"